### ISSUE TITLE
Call to add image description is not strong enough.

### ISSUE THREAD

**Issue by circuitsunfish** [learn-co-curriculum/phase-0-html-images-lab#12]
### Canvas Link

https://learning.flatironschool.com/courses/6022/assignments/193207?module_item_id=432890

### Concern

There is a call to add image descriptions in the introduction to images lesson. However, this passage uses very passive language that fails to distinguish between whether adding alternative text is technically required and whether doing so is required by regulation. In the United States, publicly accessible websites are expected to comply with the Americans with Disabilities Act and guidance under that act expects that image descriptions are present on websites. As websites are frequently the main or even only way consumers may interact with a business, it is critical to center the importance of accessibility for new web developers from the outset. 

The passage reads:
While it isn't required, it is highly recommended that every image includes an alt attribute. The alt text is important for screen readers for the visually impaired, as the text will be read out loud to the site visitor. It is also nice to provide some sort of message to a website visitor if the image fails to load, especially if the image is relevant to the rest of the content.

### Additional Context

For more guidance on accessibility standards in the United States: https://www.ada.gov/pcatoolkit/chap5toolkit.htm
For an example of the consequences of not centering accessibility in websites: https://www.cnbc.com/2019/10/07/dominos-supreme-court.html

### Suggested Changes

While alt text *isn't required for the browser*, alt text can be required for accessibility in your jurisdiction.  Your browser will not throw an error if there is no alt text with an image.  The alt text is important for screen readers for the visually impaired, as the text will be read out loud to the site visitor. Alt text also improves accessibility for non-disabled users, who will get a message if the image fails to load, especially if the image is relevant to the rest of the content.

**Comment by lizbur10** [comment]
Thanks @circuitsunfish !
